//
//  Resourses.swift
//  NewsToday
//
//  Created by Kate Kashko on 28.10.2024.
//

import Foundation

enum Resources {
    enum Text {
        static let next = "Next"
        static let getStarted = "Get started"
        static let onboardingTitle1 = "All in One Place"
        static let onboardingDescription1 = "be the first to know"
        static let onboardingTitle2 = "Choose an Article"
        static let onboardingDescription2 = "read or add to bookmarks"
        static let onboardingTitle3 = "Bookmarks"
        static let onboardingDescription3 = "all your bookmarks are here"
        static let onboardingTitle4 = "Sign in to the App"
        static let onboardingDescription4 = "to personalize the news"
        static let onboardingTitle5 = "Choose a Language"
        static let onboardingDescription5 = "english or russian"
        static let onboardingTitle6 = "Choose News Topics"
        static let onboardingDescription6 = "from many categories"
        static let onboardingTitle7 = "Select Your Favorites"
        static let onboardingDescription7 = "get personalized news"
        static let topicsTitle = "Select your favorite topics"
        static let topicsText = "Select some of your favorite topics to let us suggest better news for you"
        static let signUp = "Sign Up"
        static let signIn = "Sign In"
        static let authorizationSignInTitle = "Welcome Back 👋"
        static let authorizationSignUpTitle = "Welcome to NewsToDay"
        static let authorizationSignUpText = "I am happy to see you again. You can continue where you left off by logging in"
        static let authorizationSignInText = "Hello, I guess you are new around here. You can start using the application after sign up."
        static let alreadyHaveAnAccount = "Already have an account?"
        static let dontHaveAnAccount = "Don't have an account?"
        static let username = "Username"
        static let email = "Email"
        static let password = "Password"
        static let confirmPassword = "Confirm Password"
        static let browseTitle = "Browse"
        static let browseText = "Discover things of this world"
        static let search = "Search"
        static let recommended = "Recommended for you"
        static let seeAll = "See All"
        static let bookmarksTitle = "Bookmarks"
        static let bookmarksText = "Saved articles to the library"
        static let bookmarksNote = "You haven’t saved any articles yet. Start reading and bookmarking them now"
        static let profile = "Profile"
        static let lang = "Language"
        static let termsAndConditions = "Terms & Conditions"
        static let signOut = "Sign Out"
        static let termsAndConditionsText = ""
        static let english = "English"
        static let russian = "Russian"
        static let categoriesTitle = "Categories"
        static let categoriesText = "Thousands of articles in each category"
        
        static let politics = "⚖️ Politics"
        static let other = "❓ Other"
        static let environment = "🌍 Environment"
        static let world = "🌐 World"
        static let food = "🍗 Food"
        static let entertainment = "🎭 Entertainment"
        static let top = "🏆 Top"
        static let domestic = "🏠 Domestic"
        static let health = "🏥 Health"
        static let lifestyle = "👟 Lifestyle"
        static let crime = "👹 Crime"
        static let business = "💰 Business"
        static let technology = "💻 Technology"
        static let education = "📚 Education"
        static let science = "🔬 Science"
        static let sport = "⚽️ Sports"
    }
}
